import { NavItem } from '@/types';

export const navItems: NavItem[] = [
  /*{
    title: 'Dashboard',
    href: '/dashboard',
    icon: 'dashboard',
    label: 'Dashboard'
  },*/
  {
    title: 'المستخدمين',
    href: '/dashboard/users',
    icon: 'user',
    label: 'users'
  },
  {
    title: 'الكتب',
    href: '/dashboard/books',
    icon: 'book',
    label: 'books'
  },
  {
    title: 'إضافة كتاب',
    href: '/dashboard/book',
    icon: 'add',
    label: 'addBook'
  },
  {
    title: 'المؤلفون',
    href: '/dashboard/writers',
    icon: 'writers',
    label: 'writers'

  },
  {
    title: 'الطلبات',
    href: '/dashboard/orders',
    icon: 'order',
    label: 'orders'
  },
  {
    title: 'الإعلانات',
    href: '/dashboard/banners',
    icon: 'banner',
    label: 'banners'
  },
  {
    title: 'إضافة إعلان',
    href: '/dashboard/banner',
    icon: 'add',
    label: 'banner'
  },

  {
    title: 'الفعاليات',
    href: '/dashboard/events',
    icon: 'events',
    label: 'events'
  },

  {
    title: 'إضافة فعالية',
    href: '/dashboard/event',
    icon: 'add',
    label: 'event'
  },
  {
    title: 'العروض',
    href: '/dashboard/offers',
    icon: 'offers',
    label: 'offers'
  },  {
    title: 'إضافة عرض',
    href: '/dashboard/offer',
    icon: 'add',
    label: 'offer'
  },
  {
    title: 'تسجيل الخروج',
    href: '/',
    icon: 'login',
    label: 'logOut'
  }
];

export const nationalities = [
  { value: "أفغاني", label: "أفغاني" },
  { value: "ألباني", label: "ألباني" },
  { value: "جزائري", label: "جزائري" },
  { value: "أمريكي", label: "أمريكي" },
  { value: "أندوري", label: "أندوري" },
  { value: "أنغولي", label: "أنغولي" },
  { value: "انتيغوا", label: "انتيغوا" },
  { value: "أرجنتيني", label: "أرجنتيني" },
  { value: "أرميني", label: "أرميني" },
  { value: "أسترالي", label: "أسترالي" },
  { value: "نمساوي", label: "نمساوي" },
  { value: "أذربيجاني", label: "أذربيجاني" },
  { value: "باهامى", label: "باهامى" },
  { value: "بحريني", label: "بحريني" },
  { value: "بنجلاديشي", label: "بنجلاديشي" },
  { value: "باربادوسي", label: "باربادوسي" },
  { value: "بربودا", label: "بربودا" },
  { value: "بوتسواني", label: "بوتسواني" },
  { value: "بيلاروسي", label: "بيلاروسي" },
  { value: "بلجيكي", label: "بلجيكي" },
  { value: "بليزي", label: "بليزي" },
  { value: "بنيني", label: "بنيني" },
  { value: "بوتاني", label: "بوتاني" },
  { value: "بوليفي", label: "بوليفي" },
  { value: "بوسني", label: "بوسني" },
  { value: "برازيلي", label: "برازيلي" },
  { value: "بريطاني", label: "بريطاني" },
  { value: "بروناى", label: "بروناى" },
  { value: "بلغاري", label: "بلغاري" },
  { value: "بوركيني", label: "بوركيني" },
  { value: "بورمي", label: "بورمي" },
  { value: "بوروندي", label: "بوروندي" },
  { value: "كمبودي", label: "كمبودي" },
  { value: "كاميروني", label: "كاميروني" },
  { value: "كندي", label: "كندي" },
  { value: "االرأس الأخضر", label: "االرأس الأخضر" },
  { value: "وسط أفريقيا", label: "وسط أفريقيا" },
  { value: "تشادي", label: "تشادي" },
  { value: "شيلي", label: "شيلي" },
  { value: "صينى", label: "صينى" },
  { value: "كولومبي", label: "كولومبي" },
  { value: "جزر القمر", label: "جزر القمر" },
  { value: "كونغولي", label: "كونغولي" },
  { value: "كوستاريكي", label: "كوستاريكي" },
  { value: "كرواتية", label: "كرواتية" },
  { value: "كوبي", label: "كوبي" },
  { value: "قبرصي", label: "قبرصي" },
  { value: "تشيكي", label: "تشيكي" },
  { value: "دانماركي", label: "دانماركي" },
  { value: "جيبوتي", label: "جيبوتي" },
  { value: "دومينيكاني", label: "دومينيكاني" },
  { value: "هولندي", label: "هولندي" },
  { value: "تيموري شرقي", label: "تيموري شرقي" },
  { value: "اكوادوري", label: "اكوادوري" },
  { value: "مصري", label: "مصري" },
  { value: "إماراتي", label: "إماراتي" },
  { value: "غيني  استوائي", label: "غيني  استوائي" },
  { value: "إريتري", label: "إريتري" },
  { value: "إستوني", label: "إستوني" },
  { value: "حبشي", label: "حبشي" },
  { value: "فيجي", label: "فيجي" },
  { value: "فلبيني", label: "فلبيني" },
  { value: "فنلندي", label: "فنلندي" },
  { value: "فرنسي", label: "فرنسي" },
  { value: "جابوني", label: "جابوني" },
  { value: "غامبيي", label: "غامبيي" },
  { value: "جورجي", label: "جورجي" },
  { value: "ألماني", label: "ألماني" },
  { value: "غاني", label: "غاني" },
  { value: "إغريقي", label: "إغريقي" },
  { value: "جرينادي", label: "جرينادي" },
  { value: "غواتيمالي", label: "غواتيمالي" },
  { value: "غيني بيساوي", label: "غيني بيساوي" },
  { value: "غيني", label: "غيني" },
  { value: "جوياني", label: "جوياني" },
  { value: "هايتي", label: "هايتي" },
  { value: "هرسكي", label: "هرسكي" },
  { value: "هندوراسي", label: "هندوراسي" },
  { value: "هنغاري", label: "هنغاري" },
  { value: "إيسلندي", label: "إيسلندي" },
  { value: "هندي", label: "هندي" },
  { value: "إندونيسي", label: "إندونيسي" },
  { value: "إيراني", label: "إيراني" },
  { value: "عراقي", label: "عراقي" },
  { value: "إيرلندي", label: "إيرلندي" },
  { value: "إيطالي", label: "إيطالي" },
  { value: "إفواري", label: "إفواري" },
  { value: "جامايكي", label: "جامايكي" },
  { value: "ياباني", label: "ياباني" },
  { value: "أردني", label: "أردني" },
  { value: "كازاخستاني", label: "كازاخستاني" },
  { value: "كيني", label: "كيني" },
  { value: "كيتياني ونيفيسياني", label: "كيتياني ونيفيسياني" },
  { value: "كويتي", label: "كويتي" },
  { value: "قيرغيزستان", label: "قيرغيزستان" },
  { value: "لاوسي", label: "لاوسي" },
  { value: "لاتفي", label: "لاتفي" },
  { value: "لبناني", label: "لبناني" },
  { value: "ليبيري", label: "ليبيري" },
  { value: "ليبي", label: "ليبي" },
  { value: "ليختنشتايني", label: "ليختنشتايني" },
  { value: "لتواني", label: "لتواني" },
  { value: "لكسمبرغي", label: "لكسمبرغي" },
  { value: "مقدوني", label: "مقدوني" },
  { value: "مدغشقري", label: "مدغشقري" },
  { value: "مالاوى", label: "مالاوى" },
  { value: "ماليزي", label: "ماليزي" },
  { value: "مالديفي", label: "مالديفي" },
  { value: "مالي", label: "مالي" },
  { value: "مالطي", label: "مالطي" },
  { value: "مارشالي", label: "مارشالي" },
  { value: "موريتاني", label: "موريتاني" },
  { value: "موريشيوسي", label: "موريشيوسي" },
  { value: "مكسيكي", label: "مكسيكي" },
  { value: "ميكرونيزي", label: "ميكرونيزي" },
  { value: "مولدوفي", label: "مولدوفي" },
  { value: "موناكو", label: "موناكو" },
  { value: "منغولي", label: "منغولي" },
  { value: "مغربي", label: "مغربي" },
  { value: "ليسوتو", label: "ليسوتو" },
  { value: "لتسواني", label: "لتسواني" },
  { value: "موزمبيقي", label: "موزمبيقي" },
  { value: "ناميبي", label: "ناميبي" },
  { value: "ناورو", label: "ناورو" },
  { value: "نيبالي", label: "نيبالي" },
  { value: "هولندي", label: "هولندي" },
  { value: "نيوزيلندي", label: "نيوزيلندي" },
  { value: "نيكاراغوي", label: "نيكاراغوي" },
  { value: "نيجيري", label: "نيجيري" },
  { value: "نيجيرياني", label: "نيجيرياني" },
  { value: "نورويجي", label: "نورويجي" },
  { value: "عماني", label: "عماني" },
  { value: "باكستاني", label: "باكستاني" },
  { value: "بالاوي", label: "بالاوي" },
  { value: "بنمي", label: "بنمي" },
  { value: "بابوياني", label: "بابوياني" },
  { value: "بارغواي", label: "بارغواي" },
  { value: "بيروفي", label: "بيروفي" },
  { value: "فلبيني", label: "فلبيني" },
  {value:"فلسطيني" , label:"فلسطيني"}, 
  { value: "بولندي", label: "بولندي" },
  { value: "برتغالي", label: "برتغالي" },
  { value: "قطري", label: "قطري" },
  { value: "روسي", label: "روسي" },
  { value: "رواندي", label: "رواندي" },
  { value: "ساموائي", label: "ساموائي" },
  { value: "سان مارينو", label: "سان مارينو" },
  { value: "سعودي", label: "سعودي" },
  { value: "سنغالي", label: "سنغالي" },
  { value: "سربي", label: "سربي" },
  { value: "سيشلي", label: "سيشلي" },
  { value: "سنغافوري", label: "سنغافوري" },
  { value: "سلوفاكي", label: "سلوفاكي" },
  { value: "سلوفيني", label: "سلوفيني" },
  { value: "صومالي", label: "صومالي" },
  { value: "جنوب أفريقي", label: "جنوب أفريقي" },
  { value: "إسباني", label: "إسباني" },
  { value: "سريلانكي", label: "سريلانكي" },
  { value: "سوداني", label: "سوداني" },
  { value: "سورينامي", label: "سورينامي" },
  { value: "سويدي", label: "سويدي" },
  { value: "سويسري", label: "سويسري" },
  { value: "سوري", label: "سوري" },
  { value: "تايواني", label: "تايواني" },
  { value: "طاجيكي", label: "طاجيكي" },
  { value: "تنزاني", label: "تنزاني" },
  { value: "تايلاندي", label: "تايلاندي" },
  { value: "توغولي", label: "توغولي" },
  { value: "تونسي", label: "تونسي" },
  { value: "تركي", label: "تركي" },
  { value: "تركماني", label: "تركماني" },
  { value: "أوغندي", label: "أوغندي" },
  { value: "أوكراني", label: "أوكراني" },
  { value: "أوروغوياني", label: "أوروغوياني" },
  { value: "أوزبكي", label: "أوزبكي" },
  { value: "فانواتو", label: "فانواتو" },
  { value: "فنزويلي", label: "فنزويلي" },
  { value: "فيتنامي", label: "فيتنامي" },
  { value: "زامبي", label: "زامبي" },
  { value: "زيمبابوي", label: "زيمبابوي" }
];
